services:
  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: apm
      POSTGRES_USERS_USER: postgres
      POSTGRES_PASSWORD: P@ssw0rd1

  pgadmin:
    depends_on:
      - postgres
    image: dpage/pgadmin4
    restart: always
    ports:
      - "8081:80"
    environment:
      - SERVER_MODE=true
      - PGADMIN_DEFAULT_EMAIL=tsl@demo.com.cn
      - PGADMIN_DEFAULT_PASSWORD=pgadmin

  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --requirepass Cherry@123

  mongo:
    image: mongo
    restart: always
    networks:
      - db
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=apm_measure
      - MONGO_INITDB_ROOT_USERNAME=mongoadmin
      - MONGO_INITDB_ROOT_PASSWORD=mongoadmin

  mongo-express:
    depends_on:
      - mongo
    image: mongo-express
    restart: always
    networks:
      - db
    ports:
      - "8088:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_ENABLE_ADMIN=true
      - ME_CONFIG_BASICAUTH_USERNAME=mongoexpress
      - ME_CONFIG_BASICAUTH_PASSWORD=mongoexpress
      - ME_CONFIG_MONGODB_ADMINUSERNAME=mongoadmin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=mongoadmin
    
  zookeeper:
    image: wurstmeister/zookeeper
    restart: always
    ports:
      - 2181:2181

  kafka:
    image: wurstmeister/kafka
    restart: always
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    privileged: true
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://:9092
      KAFKA_BROKER_ID: 1

networks:
  db:
    driver: bridge